name: analysis
channels:
  - conda-forge
dependencies:
  - root
  - pip
  - protobuf=3.18.0
  - uproot3
  - uproot
  - awkward
  - pandas
  - numpy
  - lmfit
  - scikit-learn
  - keras
  - np_utils
  - tensorflow
  - matplotlib
  - vector 
  - jupyterlab_latex
